services:
  web:
    restart: always
    ports:
      - "80:8000"
    volumes: 
      - .:/hemaScorecard
    build:
      context: .
      dockerfile_inline: |
        FROM php:7.4-cli
        RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
        # RUN pecl install xdebug-3.1.5 && docker-php-ext-enable xdebug
    command: "php -S 0.0.0.0:8000 -t /hemaScorecard"
    # environment:
    #   XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    links:
      - db

  db:
    image: "mariadb:11"
    restart: always

    environment:
      MARIADB_DATABASE: ScorecardV5
      MARIADB_USER: user
      MARIADB_PASSWORD: passw0rd
      MARIADB_ROOT_PASSWORD: passw0rd
      MARIADB_AUTO_UPGRADE: "true"

    volumes:
      - db-data:/var/lib/mysql
      - ./includes:/docker-entrypoint-initdb.d

volumes:
  db-data:
